name: Build and publish
on:
  push:
    branches:
      - "*"
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to TESTpypi
        uses: JRubics/poetry-publish@v1.17
        if: github.ref == 'refs/heads/main'
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN_TEST }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          plugins: "poetry-dynamic-versioning[plugin]"
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        if: github.event_name == 'release'
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          plugins: "poetry-dynamic-versioning[plugin]"
